name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,ubuntu-22.04,macOS-11,macOS-12]
    steps:
      - uses: actions/checkout@v3
      - run: make -j4
      - run: ./tivars_tests
